<Project>

    <PropertyGroup>
        <Company>Dust in the Wind</Company>
        <Product>INS Toolkit</Product>
        <Copyright>Copyright © 2026 Dust in the Wind</Copyright>
        <Version>0.0.0.0</Version>
        <Description>A library that helps working with files and data from INS (Romanian National Statistics Institute).</Description>
        <PackageTags>ins inflation statistics</PackageTags>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <PackageProjectUrl>https://github.com/lastunicorn/ins-toolkit</PackageProjectUrl>
        <RepositoryUrl>https://github.com/lastunicorn/ins-toolkit</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="" Link="LICENSE"/>
        <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="" Link="README.md"/>
    </ItemGroup>

</Project>
